berckbelapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('showcase.urls')),
    path('urlshortener/', include('urlshortener.urls')),
]

showcase/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,)
]

urlshortener/urls.py
from django.urls import path
from . import views

app_name = "urlshortener"
urlpatterns = [
    path('', views.index,),
    path('create/', views.create, name="create",),
    path('urlredirect/<str:hash>', views.hash_redirect, name="hash_redirect",)
]

showcase/models.py
from django.db import models

# Create your models here.

urlshortener/models.py
from django.db import models

# Create your models here.
class UrlShort(models.Model):
    original_url = models.URLField(max_length=255, unique=True, null=False, blank=False)
    url_hash = models.TextField(max_length=255, unique=True, null=False, blank=False)

showcase/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'showcase/projects.html')

urlshortener/views.py
from django.shortcuts import render, redirect
from .helpers.url_helper import validate_url
from .models import UrlShort
import uuid
import hashlib
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    objects_list = UrlShort.objects.all()
    p = Paginator(objects_list, 6)
    page = request.GET.get("page")
    shorts_page = p.get_page(page)

    shorts = []
    base_url = request.build_absolute_uri('/')
    
    for object in shorts_page:
        url_hash_redirect = base_url + 'urlshortener/urlredirect/' + object.url_hash
        origin_domain = object.original_url.split('/')[2]
        shorts.append({'url_hash': url_hash_redirect, 'hash': object.url_hash, 'origin': origin_domain})

    return render(request, 'urlshortener/create.html', {
        'shorts': shorts,
        'shorts_page': shorts_page,
    })

def create(request):
    original_url = request.POST.get('original_url', None)

    if not original_url:
        return render(request, 'urlshortener/create.html', {
            'error_msg': 'url required'
        })
    
    if not validate_url(original_url):
        return render(request, 'urlshortener/create.html', {
            'error_msg': 'not valid url'
        })
    
    q = UrlShort.objects.filter(original_url=original_url)

    if len(q):
        url_object = q.first()
        result_url_hash = url_object.url_hash
        base_url = request.build_absolute_uri('/')
        url_hash_redirect = base_url + 'urlshortener/urlredirect/' + url_object.url_hash
        return render(request, 'urlshortener/short_result.html', {
            'hash': result_url_hash,
            'url_hash_redirect': url_hash_redirect
        })
    else:
        unique_id = uuid.uuid4().hex
        hash_object = hashlib.sha256(unique_id.encode())
        new_hash = hash_object.hexdigest()
        new_url_short = UrlShort.objects.create(url_hash=new_hash, original_url=original_url)
        new_url_short.save()

        base_url = request.build_absolute_uri('/')
        url_hash_redirect = base_url + new_url_short.url_hash
        return render(request, 'urlshortener/short_result.html', {
            'hash': new_url_short.url_hash,
            'url_hash_redirect': url_hash_redirect
        })

def hash_redirect(request, hash):
    objects = UrlShort.objects.filter(url_hash=hash)
    url = objects.first()
    if url:
        return redirect(url.original_url)
    else:
        return render(request, 'urlshortener/create.html', {
            'error_msg': 'not rediect found'
        })

showcase/templates/showcase/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Raul Mogollon{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'showcase/css/base.css' %}">

    {% block contentstyles %}
    <!-- content styles -->
    {% endblock %}
</head>

<body>
    <header>
        <img src="{% static 'showcase/images/raul_mogollon.jpeg' %}" alt="raul mogollon">
        <section>
            <h1>Raul Mogollon</h1>
            <p>
                Systems Engineer with experience in web development, using technologies such as React, Python,
                HTML, JavaScript, CSS, and PHP with Magento2. Additionally, I have knowledge in creating and consuming
                RESTful APIs in various programming languages. I apply both Backend and Frontend development roles
                using SCRUM methodologies. Furthermore, I have a B2 level of competence in English,
                which means I speak the language fluently.
            </p>
        </section>
    </header>

    <section class="work-experience">
        <h1>Work Experience</h1>
        <p>
            <strong>OMNI.PRO:</strong> As a Systems Engineer, I worked as a Backend Developer, responsible for
            creating web-based e-commerce systems for the company's various clients. I used programming
            languages such as PHP, along with technologies like Magento2 and GIT & GITHUB. Additionally, I implemented
            a REST API architecture using MySQL. Furthermore, I performed website maintenance, using
            JavaScript and PHP to make modifications requested by clients, following the Agile SCRUM methodology.
        </p>
    </section>

    <main>
        {% block content %}
        <!-- content -->
        {% endblock %}
    </main>

    <section class="console-section">
        <h2>ls -l My skills/</h2>
        <ul>
            <li>drwxr-xr-x 4 raulm raulm 4096 English</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 Linux</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 PHP</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 Magento2</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 Python</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 Django</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 MySQL</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 React</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 React Native</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 Flutter</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 Angular</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 HTML5</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 CSS3</li>
            <li>drwxr-xr-x 4 raulm raulm 4096 JavaScript</li>
        </ul>
    </section>

    <footer>
        <a href="https://github.com/Berckbel" target="_blank">
            <img src="{% static 'showcase/images/github.png' %}" alt="github">
        </a>
        <a href="https://www.linkedin.com/in/raul-mogollon-49a24a278/" target="_blank">
            <img src="{% static 'showcase/images/linkedin.png' %}" alt="linkedin">
        </a>
        <p id="berckbel-copyright">&copy; 202# Raul Mogollon</p>
    </footer>

    <script src="{% static 'showcase/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'showcase/js/showcase.js' %}"></script>
</body>

</html>

showcase/templates/showcase/projects.html
{% extends 'showcase/layout/base.html' %}

{% load static %}

{% block contentstyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'showcase/css/projects.css' %}">
{% endblock %}

{% block content %}
<div class="title-projects">
    <h1>Projects</h1>
</div>
<section class="projects-container">
    <div class="project-card">
        <h2>Berckbel Blog</h2>
        <img src="{% static 'showcase/images/bloghome.png' %}" alt="blog image">
        <p>
            This is my personal blog, which I created for people to share their opinions on various topics.
        </p>
        <h3>Technologies</h3>
        <ul>
            <li>Django</li>
            <li>JWT</li>
            <li>REST API</li>
            <li>React</li>
            <li>TypeScript</li>
            <li>Tailwind</li>
            <li>PostgreSQL</li>
            <li>Git and GitHub</li>
            <li>Linux</li>
            <li>Nginx</li>
        </ul>
        <a href="https://berckbelblog.berckbel.com" target="_blank">View the app</a>
    </div>
    <div class="project-card">
        <h2>URL Shortener</h2>
        <img src="{% static 'showcase/images/url_shortener.png' %}" alt="taskmanager image">
        <p>
            This is my url shortener that helps people to share big urls.
        </p>
        <h3>Technologies</h3>
        <ul>
            <li>Django</li>
            <li>PostgreSQL</li>
            <li>Git and GitHub</li>
            <li>Linux</li>
            <li>Nginx</li>
        </ul>
        <a href="https://www.berckbel.com/urlshortener" target="_blank">View the app</a>
    </div>
    <div class="project-card">
        <h2>Task Manager</h2>
        <img src="{% static 'showcase/images/taskmanager.png' %}" alt="taskmanager image">
        <p>
            This is my task management app, which I created to help people manage their tasks in an organized way.
        </p>
        <h3>Technologies</h3>
        <ul>
            <li>Django</li>
            <li>JWT</li>
            <li>REST API</li>
            <li>React</li>
            <li>Tailwind</li>
            <li>PostgreSQL</li>
            <li>Git and GitHub</li>
            <li>Linux</li>
            <li>Nginx</li>
        </ul>
        <a href="https://taskmanager.berckbel.com" target="_blank">View the app</a>
    </div>
    <div class="project-card">
        <h2>PokeDex</h2>
        <img src="{% static 'showcase/images/pokedex.png' %}" alt="pokedex image">
        <p>
            This is my mobile app, which clones a PokeDex and includes the game "Who's That Pokemon?"
        </p>
        <h3>Technologies</h3>
        <ul>
            <li>REST API</li>
            <li>React Native</li>
            <li>Git and GitHub</li>
            <li>Linux</li>
            <li>Expo</li>
        </ul>
        <a href="{% static 'showcase/apk/MogoDex.apk' %}" download>Download link</a>
    </div>
    <div class="project-card">
        <h2>Pokemon Web</h2>
        <img src="{% static 'showcase/images/webpokemon.png' %}" alt="pokedex image">
        <p>
            This is my Pokemon web app, which I created for fun. It uses the PokeAPI to list Pokémon and view their stats. The app looks great!
        </p>
        <h3>Technologies</h3>
        <ul>
            <li>REST API</li>
            <li>JavaScript</li>
            <li>CSS</li>
            <li>jQuery</li>
            <li>Linux</li>
            <li>Git and GitHub</li>
        </ul>
        <a href="https://berckbel.github.io/web-pokemon/" target="_blank">View the app</a>
    </div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Raul Mogollon</title>
</head>
<body>
    {% block content %}
        <!-- content -->
    {% endblock %}
</body>
</html>

urlshortener/templates/urlshortener/create.html
{% extends 'urlshortener/layout/base.html' %}

{% load static %}

{% block contentstyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'urlshortener/css/create.css' %}">
{% endblock %}

{% block content %}
<section class="create-section">
    <form action="{% url 'urlshortener:create' %}" method="post">
        {% csrf_token %}
        <label for="original_url">
            Insert your Url here
        </label>
        <input type="text" name="original_url" id="original_url">
        {% if error_msg %}
            <p><strong style="color: red; margin: 20px;" >{{ error_msg }}</strong></p>
        {% endif %}
        <button type="submit">Generate</button>
    </form>
</section>
<section class="create-list-section">
    {% if shorts|length > 0 %}
        <table>
            <thead>
                <tr>
                    <th>Short</th>
                    <th>Domain</th>
                </tr>
            </thead>
            <tbody>
                {% for short in shorts %}
                    <tr>
                        <td>
                            <a href="{{ short.url_hash }}">{{ short.hash }}</a>
                        </td>
                        <td>
                            <span>{{ short.origin }}</span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            {% if shorts_page.has_previous %}
                <a href="?page={{ shorts_page.previous_page_number }}">&laquo;</a>
            {% endif %}
            <span>{{ shorts_page.number }}</span>
            {% if shorts_page.has_next %}
                <a href="?page={{ shorts_page.next_page_number }}">&raquo;</a>
            {% endif %}
        </div>
    {% endif %}
</section>
{% endblock %}

urlshortener/templates/urlshortener/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Raul Mogollon{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'urlshortener/css/base.css' %}">

    {% block contentstyles %}
    <!-- content styles -->
    {% endblock %}
</head>

<body>
    <header>
        <section>
            <h1>Url Shortener</h1>
            <p>
                Url Shortener, by Berckbel
            </p>
        </section>
    </header>

    <main>
        {% block content %}
        <!-- content -->
        {% endblock %}
    </main>

    <footer>
        <a href="https://github.com/Berckbel" target="_blank">
            <img src="{% static 'showcase/images/github.png' %}" alt="github">
        </a>
        <a href="https://www.linkedin.com/in/raul-mogollon-49a24a278/" target="_blank">
            <img src="{% static 'showcase/images/linkedin.png' %}" alt="linkedin">
        </a>
        <p>&copy; 2024 Raul Mogollon</p>
    </footer>

    <script src="{% static 'showcase/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'showcase/js/showcase.js' %}"></script>
</body>

</html>

urlshortener/templates/urlshortener/short_result.html
{% extends 'urlshortener/layout/base.html' %}

{% load static %}

{% block contentstyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'urlshortener/css/short_result.css' %}">
{% endblock %}

{% block content %}
<section class="result-section">
    <div>
        <h1>Hash Result</h1>
        {% if hash %}
            <p>{{ hash }}</p>
        {% endif %}
    </div>
    <div>
        <h1>Short Result</h1>
        {% if url_hash_redirect %}
            <p>{{ url_hash_redirect }}</p>
        {% endif %}
    </div>
</section>
{% endblock %}